### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by PaluMacil** [cakturk/go-netstat#1]
Since the command netstat exists on Windows, it would be good to either add a help wanted to this issue so that someone like me could come along and add support. If you don't think this is in scope for this library, I could make a PR to mention that it is Linux only in the README. I am not familiar with BSD, so I don't know if that would be easy to add (or even identical to Linux), but I'd be willing to try that out too (but it might be at a much later date).

**Comment by cakturk** [comment]
Hello @PaluMacil 

I'm sorry for the late reply. I added Windows support for the library. I would appreciate if you could test these changes and give feedback. If you find that the changes are sufficient for Windows support, you can close this issue.

As for BSD support, I think the implementation difficulty would be on a par with Windows or a little bit harder. If you plan to add support for FreeBSD, I think you can use the information below as a guide.

https://svnweb.freebsd.org/base/release/11.0.0/usr.bin/sockstat/sockstat.c?view=markup#l571

If you have any changes that you think will be useful, you can always make a PR. Contributions are always appreciated.

**Comment by PaluMacil** [comment]
I still need to test this but am traveling for a week, and I'm not sure if I can go much till I return, but I will try to address the Windows testing upon my return.

**Comment by cakturk** [comment]
Closing due to further inactivity.
